load_dir: ~/ehrensberger/RoboNet/hdf5/
save_dir: ~/ehrensberger/RoboNetCustomized/hdf5/
# scale: str = 'symmetric' ([1, 1]) | 'min_max' ([0, 1])
norm: symmetric 

robot: 'baxter'
horizon: 16 

plot: 
  figure: 
    figsize: (10, 5)

  histogram: 
    matplotlib: 
      density: True 
      stacked: True
      edgecolor: black 
      alpha: 0.75

    seaborn: 
      multiple: dodge
      kde: True
